Plan 837 clyde oauth
PlanoramaEvents/planorama pull request #844
Opened 2023-06-08 22:17 UTC by balen

This is the authentication part

Linking a planorama user account to clyde will be a separate PR (as will the API batch jobs to sync)

2023-06-10 18:28 UTC, Gailbear approved these changes

2023-06-10 18:28 UTC, Gailbear commented on app/services/identity_service.rb
> +      password: (0...50).map { ('a'..'z').to_a[rand(26)] }.join,
this is a horrible password generation method lol please just use a uuid

2023-06-10 18:28 UTC, Gailbear commented on app/services/identity_service.rb
> +          Rails.logger.debug "****** CREATE PERSON #{identity.to_json}"
do we really want to be logging this? that seems like a lot of PII to put in our logs.

2023-06-10 18:35 UTC, Gailbear requested changes

2023-06-10 18:35 UTC, Gailbear commented on app/javascript/navbar/top-navbar.vue
> +        <div class="text-light mb-2">Logged in as: {{ currentUserDisplay }}</div>
this probably shouldn't be checked in as is... unless you changed it on the backend

2023-06-10 18:35 UTC, Gailbear commented on app/services/identity_service.rb
> +      password: (0...50).map { ('a'..'z').to_a[rand(26)] }.join,
Wait... why do we even need a password?

2023-06-11 13:32 UTC, balen commented on app/services/identity_service.rb
> +      password: (0...50).map { ('a'..'z').to_a[rand(26)] }.join,
we need something in there so that they are forced to reset password cause the person is generated when they login with the OAuth method, but they can also login later with the user/password method and I think people with blank or no passwords is not a good idea.

2023-06-11 13:33 UTC, balen commented on app/services/identity_service.rb
> +          Rails.logger.debug "****** CREATE PERSON #{identity.to_json}"
That was just debig while developing - will be removed

2023-06-11 13:52 UTC, balen commented on app/javascript/navbar/top-navbar.vue
> +        <div class="text-light mb-2">Logged in as: {{ currentUserDisplay }}</div>
done

2023-06-16 00:43 UTC, Gailbear approved these changes

2023-06-16 00:43 UTC, merged